### ISSUE TITLE
Update CSV compat?

### ISSUE THREAD

**Issue by longemen3000** [SimonEnsemble/PoreMatMod.jl#130]
iwas trying to install the package, but i couldn't at first because CSV is fixed at `0.8`, but the latest version of CSV is `0.10`. is it possible to change the compat to `0.8,0.9,0.10`?

**Comment by eahenle** [comment]
Yep!  Patch inbound, should be registered as `0.2.14` in just a little bit.

Thanks @longemen3000 for the heads-up on the incompatibility!
