### ISSUE TITLE
Failure to load data

### ISSUE THREAD

**Issue by sensiang705** [SimonEnsemble/PoreMatMod.jl#135]
julia> using Pkg
julia> using PoreMatMod
julia> parent = Crystal("IRMOF-1.cif")
ERROR: SystemError: opening file "C:\\Users\\user\\data\\crystals\\IRMOF-1.cif": No such file or directory
.....(a lot of error msg)
parent = Crystal("C:\\Users\\user\\.julia\\packages\\PoreMatMod\\voclm\\test\\data\\crystals\\IRMOF-1.cif")
ERROR: SystemError: opening file "C:\\Users\\user\\.julia\\packages\\PoreMatMod\\voclm\\test\\data\\crystals\\IRMOF-1.cif": No such file or directory
.....(a lot of error msg)

![image](https://user-images.githubusercontent.com/61655494/188061729-4c47eb29-eb18-467d-a5bb-ecb83e322c5a.png)
The file is really there.

I don't quite understand why. Can someone please help me? I am using version 1. Thank you very much in advance for solving this issue. I need to do geometry optimization for XYZ file in Julia.

**Comment by eahenle** [comment]
Interesting!  I don't see anything wrong with the path as you entered it...  However, I am unable to reproduce the error:
![image](https://user-images.githubusercontent.com/16201240/188140241-c12a8356-32f3-4b34-82db-5856b320f48a.png)

You can run the module's test suite by doing `import Pkg; Pkg.test("PoreMatMod")`.  The example notebook tests fail, so ignore that, but everything before that should pass:
![image](https://user-images.githubusercontent.com/16201240/188142671-7d4c88c9-cca8-4390-a158-db6f53715a1f.png)

Just a guess, but maybe your Julia session doesn't have permission to read the file?  You could try:
- Move the file to another location, like C:\Users\user\new_folder
- Starting Julia with administrative privileges

You can confirm that Julia sees the file like so:
![image](https://user-images.githubusercontent.com/16201240/188141233-9dd60bb7-8e51-4e15-bf42-a6735ceca523.png)
If that fails, build the `joinpath` sequence up folder-by-folder until you find where it stops working.

**Comment by eahenle** [comment]
@sensiang705 any update on this?
