### ISSUE TITLE
fixup_stdlib_path not found

### ISSUE THREAD

**Issue by galjos** [SimonEnsemble/PoreMatMod.jl#150]
`ERROR: LoadError:` type DataType has no field `fixup_stdlib_path` on Julia@1.9.0

**Comment by eahenle** [comment]
Hi!  Could you please provide further information regarding this error and how you encountered it?  With a fresh install of Julia 1.9.0 via [juliaup](https://github.com/JuliaLang/juliaup) on WSL Ubuntu 20.04 the following is successful:*

```
pkg> add PoreMatMod
pkg> test PoreMatMod
```

* all the unit tests pass.  There is an error in auto-testing the example notebooks, but those seem to work fine when run manually.

So, it seems the problem may be outside of `PoreMatMod`, but without knowing more about the context I can't really conclude anything.

**Comment by galjos** [comment]
`Testing PoreMatMod tests passed`. I can not reproduce the issue. It works now.
